import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    // No `remotePatterns`. Every photograph is served from `public/`, so the
    // optimiser never reaches off this origin and no page can be broken by a
    // third-party CDN. Re-adding one is a decision, not a detail.
    // Cap the ladder at 1920. Nothing on this page renders wider than ~1440
    // CSS pixels, so 2560/3840 variants only ask the optimiser to upscale
    // source files it already has at native size — slow, and no sharper.
    deviceSizes: [420, 640, 768, 1024, 1280, 1600, 1920],
    imageSizes: [160, 240, 320, 400, 512],
  },

  async redirects() {
    return [
      // Disclaimer and Refund Policy pages have been removed; these permanent
      // redirects keep any existing bookmarks or external links from 404ing.
      { source: "/disclaimer", destination: "/", permanent: true },
      { source: "/refund-policy", destination: "/terms", permanent: true },
    ];
  },

  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          // Prevents this site from being embedded in an iframe on any
          // other domain. Clickjacking mitigation.
          { key: "X-Frame-Options", value: "SAMEORIGIN" },
          // Prevents browsers from MIME-sniffing a response away from the
          // declared Content-Type.
          { key: "X-Content-Type-Options", value: "nosniff" },
          // Sends the full origin on same-origin requests; strips down to
          // origin-only on cross-origin. No query strings leak to third parties.
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          // Locks off hardware APIs this site does not use.
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=()",
          },
          {
            key: "Content-Security-Policy",
            value: [
              "default-src 'self'",
              // Next.js injects inline <script> tags during hydration; a strict
              // nonce-based CSP would require middleware-level nonce injection
              // on every request — substantially more complex than this site
              // warrants. 'unsafe-inline' is the accepted trade-off for static
              // Next.js deployments.
              "script-src 'self' 'unsafe-inline'",
              // Tailwind CSS v4 generates inline styles.
              "style-src 'self' 'unsafe-inline'",
              // All photographs are self-hosted; blur-up placeholders are
              // data: URIs generated by next/image.
              "img-src 'self' data:",
              // next/font/google self-hosts the font files — no external
              // font requests at runtime.
              "font-src 'self'",
              // Three distinct iframe locations: QuoteForm, CoverageMap,
              // and one LocationMap per community page (11 total).
              // Maps Embed API serves from www.google.com; maps.google.com
              // retained so any cached pages don't break during the rollout.
              "frame-src https://www.google.com https://maps.google.com",
              "connect-src 'self'",
              "object-src 'none'",
              "base-uri 'self'",
            ].join("; "),
          },
          // HSTS is intentionally commented out. Setting it before the
          // deployment host enforces HTTPS bricks the domain for all returning
          // visitors until max-age expires. Uncomment after confirming HTTPS
          // is active and stable at the host level.
          // { key: "Strict-Transport-Security", value: "max-age=63072000; includeSubDomains; preload" },
        ],
      },
    ];
  },
};

export default nextConfig;
